services:
  app2:
    image: 1234a4321/app2:1.1
    working_dir: /app
    volumes:
      - /path/on/host/docker-compose.yml:/app/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=<redis_host>
      - REDIS_PORT=6379
      - REDIS_DB=0
    privileged: true
